# Generated by Django 4.0.3 on 2022-03-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doc_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
