# Generated by Django 4.0.3 on 2022-03-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_doc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='number_of_vcs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='puzzles_solved',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
