# Generated by Django 4.0.3 on 2022-03-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_number_of_vcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doc_code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
