# Generated by Django 3.2.9 on 2022-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_scrapbook_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbook',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
