# Generated by Django 3.2.9 on 2022-03-09 13:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_scrapbook_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='scrapbook',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
