# Generated by Django 3.2.9 on 2022-03-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20220309_1357'),
        ('patient', '0006_scrapbook_message'),
    ]

    operations = [
    ]
