# Generated by Django 3.2.9 on 2022-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_merge_0006_auto_20220309_1357_0006_scrapbook_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbook',
            name='realation_with_patient',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scrapbook',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='family_members/'),
        ),
    ]
