# Generated by Django 3.2.9 on 2022-03-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20220309_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapbook',
            old_name='realation_with_patient',
            new_name='relation_with_patient',
        ),
    ]
