# Generated by Django 3.2.9 on 2022-03-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_memes'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='meme',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
